# Generated by Django 2.2 on 2019-04-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asker',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='info',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
