# Generated by Django 2.2 on 2019-05-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_sail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivery',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
